# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Selenium with TestNG - CI

on:
   push:
    branches: [ "Energy-Tree-Energy-Consumption-Trend-Highchart-Sprint-22" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Build with Maven
      run: mvn -B clean test 

   
